apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport
spec:
  type: NodePort
  ports:
    - name: "http-port"
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: sample-app
